<?xml version="1.0" encoding="UTF-8" ?>
<Package name="installer_pml" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="icon" src="icon.png" />
        <File name="__init__" src="abcdk/__init__.py" />
        <File name="animation_list_poses" src="abcdk/animation_list_poses.py" />
        <File name="arraytools" src="abcdk/arraytools.py" />
        <File name="blog" src="abcdk/blog.py" />
        <File name="bluez_simple_agent_patch_auto_pin_code" src="abcdk/bluez_simple_agent_patch_auto_pin_code.py" />
        <File name="bluez_test_discovery_find" src="abcdk/bluez_test_discovery_find.py" />
        <File name="blueztools" src="abcdk/blueztools.py" />
        <File name="bodytalk" src="abcdk/bodytalk.py" />
        <File name="bodytalk_movements" src="abcdk/bodytalk_movements.py" />
        <File name="bodytalk_movements_romeo" src="abcdk/bodytalk_movements_romeo.py" />
        <File name="cache" src="abcdk/cache.py" />
        <File name="camera" src="abcdk/camera.py" />
        <File name="chat" src="abcdk/chat.py" />
        <File name="choregraphetools" src="abcdk/choregraphetools.py" />
        <File name="color" src="abcdk/color.py" />
        <File name="config" src="abcdk/config.py" />
        <File name="config_sample" src="abcdk/config_sample.py" />
        <File name="constants" src="abcdk/constants.py" />
        <File name="datamatrix_topology" src="abcdk/datamatrix_topology.py" />
        <File name="debug" src="abcdk/debug.py" />
        <File name="debug_sound_analyse" src="abcdk/debug_sound_analyse.py" />
        <File name="diagnostic" src="abcdk/diagnostic.py" />
        <File name="display" src="abcdk/display.py" />
        <File name="documentation" src="abcdk/documentation.py" />
        <File name="draw_3d" src="abcdk/draw_3d.py" />
        <File name="emotion" src="abcdk/emotion.py" />
        <File name="emotion_list_eyes" src="abcdk/emotion_list_eyes.py" />
        <File name="emotion_list_poses" src="abcdk/emotion_list_poses.py" />
        <File name="emotion_list_tracking_poses" src="abcdk/emotion_list_tracking_poses.py" />
        <File name="evaltools" src="abcdk/evaltools.py" />
        <File name="extract_test" src="abcdk/extract_test.py" />
        <File name="extractortools" src="abcdk/extractortools.py" />
        <File name="facerecognition" src="abcdk/facerecognition.py" />
        <File name="filetools" src="abcdk/filetools.py" />
        <File name="generate_autotest_pnp" src="abcdk/generate_autotest_pnp.py" />
        <File name="graph" src="abcdk/graph.py" />
        <File name="humans" src="abcdk/humans.py" />
        <File name="ihmtools" src="abcdk/ihmtools.py" />
        <File name="image" src="abcdk/image.py" />
        <File name="image_info" src="abcdk/image_info.py" />
        <File name="image_morphing" src="abcdk/image_morphing.py" />
        <File name="imagePnp" src="abcdk/imagePnp.py" />
        <File name="images2gif" src="abcdk/images2gif.py" />
        <File name="kmltools" src="abcdk/kmltools.py" />
        <File name="knowledge" src="abcdk/knowledge.py" />
        <File name="knownobjectdef" src="abcdk/knownobjectdef.py" />
        <File name="laser" src="abcdk/laser.py" />
        <File name="leds" src="abcdk/leds.py" />
        <File name="melody" src="abcdk/melody.py" />
        <File name="metaphone" src="abcdk/metaphone.py" />
        <File name="misc" src="abcdk/misc.py" />
        <File name="motiondef" src="abcdk/motiondef.py" />
        <File name="motiontools" src="abcdk/motiontools.py" />
        <File name="musics" src="abcdk/musics.py" />
        <File name="naolibrary" src="abcdk/naolibrary.py" />
        <File name="naoqitools" src="abcdk/naoqitools.py" />
        <File name="nav_mark" src="abcdk/nav_mark.py" />
        <File name="navigation" src="abcdk/navigation.py" />
        <File name="navigation_live_debug_ros" src="abcdk/navigation_live_debug_ros.py" />
        <File name="nettools" src="abcdk/nettools.py" />
        <File name="numeric" src="abcdk/numeric.py" />
        <File name="numeric_signal" src="abcdk/numeric_signal.py" />
        <File name="object_list" src="abcdk/object_list.py" />
        <File name="obstacles" src="abcdk/obstacles.py" />
        <File name="path_planner" src="abcdk/path_planner.py" />
        <File name="pathtools" src="abcdk/pathtools.py" />
        <File name="patterns" src="abcdk/patterns.py" />
        <File name="persistent_memory" src="abcdk/persistent_memory.py" />
        <File name="pod" src="abcdk/pod.py" />
        <File name="poselibrary" src="abcdk/poselibrary.py" />
        <File name="profiler" src="abcdk/profiler.py" />
        <File name="pronounciation" src="abcdk/pronounciation.py" />
        <File name="qtransform" src="abcdk/qtransform.py" />
        <File name="romeo" src="abcdk/romeo.py" />
        <File name="runAutoTestPnpDatamatrix" src="abcdk/runAutoTestPnpDatamatrix.py" />
        <File name="rvizWrapper" src="abcdk/rvizWrapper.py" />
        <File name="script_test_sumo" src="abcdk/script_test_sumo.py" />
        <File name="segment_axis" src="abcdk/segment_axis.py" />
        <File name="sentence" src="abcdk/sentence.py" />
        <File name="serialization_tools" src="abcdk/serialization_tools.py" />
        <File name="serialtools" src="abcdk/serialtools.py" />
        <File name="showemotion" src="abcdk/showemotion.py" />
        <File name="skeletonlibrary" src="abcdk/skeletonlibrary.py" />
        <File name="sound" src="abcdk/sound.py" />
        <File name="sound_analyse" src="abcdk/sound_analyse.py" />
        <File name="speech" src="abcdk/speech.py" />
        <File name="stringtools" src="abcdk/stringtools.py" />
        <File name="system" src="abcdk/system.py" />
        <File name="taskmanager" src="abcdk/taskmanager.py" />
        <File name="temp_choregaphe" src="abcdk/temp_choregaphe.py" />
        <File name="test" src="abcdk/test.py" />
        <File name="test_opencvCornersDetection" src="abcdk/test_opencvCornersDetection.py" />
        <File name="testpathfinder" src="abcdk/testpathfinder.py" />
        <File name="topology" src="abcdk/topology.py" />
        <File name="topology_drawcurrentlocalmap" src="abcdk/topology_drawcurrentlocalmap.py" />
        <File name="tracking" src="abcdk/tracking.py" />
        <File name="translate" src="abcdk/translate.py" />
        <File name="tts" src="abcdk/tts.py" />
        <File name="typetools" src="abcdk/typetools.py" />
        <File name="user" src="abcdk/user.py" />
        <File name="visionrecognition" src="abcdk/visionrecognition.py" />
        <File name="christian_name_list_en" src="abcdk/data/christian_name_list_en.txt" />
        <File name="christian_name_list_fr" src="abcdk/data/christian_name_list_fr.txt" />
        <File name="humans_info" src="abcdk/data/humans_info.txt" />
        <File name="nao" src="abcdk/data/emo/nao.png" />
        <File name="nao_anger" src="abcdk/data/emo/nao_anger.png" />
        <File name="nao_excitement" src="abcdk/data/emo/nao_excitement.png" />
        <File name="nao_fear" src="abcdk/data/emo/nao_fear.png" />
        <File name="nao_happy" src="abcdk/data/emo/nao_happy.png" />
        <File name="nao_hot" src="abcdk/data/emo/nao_hot.png" />
        <File name="nao_neutral" src="abcdk/data/emo/nao_neutral.png" />
        <File name="nao_proud" src="abcdk/data/emo/nao_proud.png" />
        <File name="nao_sad" src="abcdk/data/emo/nao_sad.png" />
        <File name="haarcascade_frontalface_alt" src="abcdk/data/haarcascades/haarcascade_frontalface_alt.xml" />
        <File name="F" src="abcdk/data/images/F.png" />
        <File name="F_rotated_translated" src="abcdk/data/images/F_rotated_translated.png" />
        <File name="test_navMark_onRobot" src="abcdk/tests/test_navMark_onRobot.py" />
        <File name="test_topology" src="abcdk/tests/unit/test_topology.py" />
        <File name="detect_cube" src="abcdk/detect_cube.py" />
        <File name="figure" src="abcdk/figure.py" />
        <File name="sound_generation" src="abcdk/sound_generation.py" />
        <File name="sound_recognition" src="abcdk/sound_recognition.py" />
        <File name="sound_evaluation" src="abcdk/sound_evaluation.py" />
        <File name="actors" src="abcdk/actors.py" />
        <File name="color_tracker" src="abcdk/color_tracker.py" />
        <File name="concept_network" src="abcdk/concept_network.py" />
        <File name="menu" src="abcdk/data/html/menu.html~" />
        <File name="memory" src="abcdk/data/ticketMemory/memory.txt" />
        <File name="memory2" src="abcdk/data/ticketMemory/memory2.txt" />
        <File name="memoryBackUp" src="abcdk/data/ticketMemory/memoryBackUp.txt" />
        <File name="ticketsNews" src="abcdk/data/ticketMemory/ticketsNews.txt" />
        <File name="dialog" src="abcdk/dialog.py" />
        <File name="dodger" src="abcdk/dodger.py" />
        <File name="ector" src="abcdk/ector.py" />
        <File name="entry" src="abcdk/entry.py" />
        <File name="freespeech" src="abcdk/freespeech.py" />
        <File name="html_manager" src="abcdk/html_manager.py" />
        <File name="log_formatter" src="abcdk/log_formatter.py" />
        <File name="memory" src="abcdk/memory.py" />
        <File name="memory" src="abcdk/memory.txt" />
        <File name="memoryBackUp" src="abcdk/memoryBackUp.txt" />
        <File name="memoryMusic" src="abcdk/memoryMusic.txt" />
        <File name="memoryNews" src="abcdk/memoryNews.txt" />
        <File name="music_manager" src="abcdk/music_manager.py" />
        <File name="object_recognition_cnn" src="abcdk/object_recognition_cnn.py" />
        <File name="pepper_bot" src="abcdk/pepper_bot.py" />
        <File name="__init__" src="abcdk/python_speech_features/__init__.py" />
        <File name="base" src="abcdk/python_speech_features/base.py" />
        <File name="sigproc" src="abcdk/python_speech_features/sigproc.py" />
        <File name="rodin" src="abcdk/rodin.py" />
        <File name="romeo_stereo" src="abcdk/romeo_stereo.py" />
        <File name="sensorShow" src="abcdk/sensorShow.py" />
        <File name="sensorShow" src="abcdk/sensorShow.py~" />
        <File name="sentence_generator" src="abcdk/sentence_generator.py" />
        <File name="ReadMe" src="abcdk/serverNews/ReadMe.txt" />
        <File name="ReadMe" src="abcdk/serverNews/ReadMe.txt~" />
        <File name="bonjour" src="abcdk/serverNews/bonjour.php" />
        <File name="style" src="abcdk/serverNews/css/style.css" />
        <File name="DINRoundOffcPro-Black" src="abcdk/serverNews/font/DINRoundOffcPro-Black.ttf" />
        <File name="DINRoundOffcPro" src="abcdk/serverNews/font/DINRoundOffcPro.ttf" />
        <File name="formNews" src="abcdk/serverNews/formNews.html" />
        <File name="formNews" src="abcdk/serverNews/formNews.html~" />
        <File name="backMenu" src="abcdk/serverNews/img/backMenu.png" />
        <File name="background" src="abcdk/serverNews/img/background.png" />
        <File name="buttons" src="abcdk/serverNews/img/buttons.pdn" />
        <File name="moins" src="abcdk/serverNews/img/moins.png" />
        <File name="moinsSombre" src="abcdk/serverNews/img/moinsSombre.png" />
        <File name="new_message" src="abcdk/serverNews/img/new_message.png" />
        <File name="next" src="abcdk/serverNews/img/next.png" />
        <File name="nextMenu" src="abcdk/serverNews/img/nextMenu.png" />
        <File name="nextSombre" src="abcdk/serverNews/img/nextSombre.png" />
        <File name="pause" src="abcdk/serverNews/img/pause.png" />
        <File name="pauseSombre" src="abcdk/serverNews/img/pauseSombre.png" />
        <File name="plus" src="abcdk/serverNews/img/plus.png" />
        <File name="plusSombre" src="abcdk/serverNews/img/plusSombre.png" />
        <File name="previous" src="abcdk/serverNews/img/previous.png" />
        <File name="previousSombre" src="abcdk/serverNews/img/previousSombre.png" />
        <File name="start" src="abcdk/serverNews/img/start.png" />
        <File name="startsombre" src="abcdk/serverNews/img/startsombre.png" />
        <File name="stop" src="abcdk/serverNews/img/stop.png" />
        <File name="stopSombre" src="abcdk/serverNews/img/stopSombre.png" />
        <File name="index" src="abcdk/serverNews/index.html" />
        <File name="save2" src="abcdk/serverNews/save2.php" />
        <File name="saveInText" src="abcdk/serverNews/saveInText.php" />
        <File name="saveInText" src="abcdk/serverNews/saveInText.php~" />
        <File name="slam_tools" src="abcdk/slam_tools.py" />
        <File name="socket_receive" src="abcdk/socket_receive.py" />
        <File name="socket_send" src="abcdk/socket_send.py" />
        <File name="sound_analyser" src="abcdk/sound_analyser.py" />
        <File name="sound_processor" src="abcdk/sound_processor.py" />
        <File name="testMusicMaxime" src="abcdk/testMusicMaxime.py" />
        <File name="test_ticket" src="abcdk/test_ticket.py" />
        <File name="text_comprehension" src="abcdk/text_comprehension.py" />
        <File name="ticket" src="abcdk/ticket.py" />
        <File name="wiki_scrapper" src="abcdk/wiki_scrapper.py" />
        <File name="wordnet" src="abcdk/wordnet.py" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src="abcdk/data/metaData.csv" />
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
