anims_map = {    # for each animation, the list of words that can be expressed with this animation (in lower case)

    # **********
    "Angry": [],
    "BowShort": [],
    "But": [],
    "CalmDown": [],
    "Choice": [],
    "ComeOn": [],
    "Confused": [],
    "CountFive": [],
    "CountFour": [],
    "CountMore": [],
    "CountOne": [],
    "CountThree": [],
    "CountTwo": [],
    "Desperate": [],
    "DontUnderstand": [],
    "Enthusiastic": [],
    "Everything": [],
    "Excited": [],
    "Explain": [],
    "Far": [],
    "Follow": [],
    "Give": [],
    "Great": [],
    "HeSays": [],
    "Hey": [],
    "Hide": [],
    "Hot": [],
    "IDontKnow": [],
    "Joy": [],
    "Kisses": [],
    "Look": [],
    "Maybe": [],
    "Me": ["I"],
    "Mime": [],
    "Next": [],
    "No": [],
    "Nothing": [],
    "OnTheEvening": [],
    "Please": [],
    "Reject": [],
    "Salute": [],
    "ShowFloor": [],
    "ShowSky": [],
    "ShowTablet": [],
    "Shy": [],
    "Stretch": [],
    "Surprised": [],
    "Take": [],
    "TakePlace": [],
    "Thinking": [],
    "This": [],
    "WhatSThis": [],
    "Whisper": [],
    "Wings": [],
    "Yes": [],
    "You": [],
    "YouKnowWhat": [],
    "Yum": [],

    # **********
    # WRN: skipping the anim 'Confused' (already in another library)
    "Alienated": [],
    "AskForAttention": [],
    "Cautious": [],
    "Determined": [],
    "Embarrassed": [],
    "Hesitation": [],
    "Innocent": [],
    "Lonely": [],
    "Mischievous": [],
    "Puzzled": [],
    "Sneeze": [],
    "Stubborn": [],
    "Suspicious": [],

    # **********
    # WRN: skipping the anim 'Angry' (already in another library)
    # WRN: skipping the anim 'Angry' (already in another library)
    # WRN: skipping the anim 'Angry' (already in another library)
    # WRN: skipping the anim 'Angry' (already in another library)
    "Anxious": [],
    "Bored": [],
    "Disappointed": [],
    "Exhausted": [],
    "Fear": [],
    "Fearful": [],
    "Frustrated": [],
    "Humiliated": [],
    "Hurt": [],
    "Late": [],
    "Sad": [],
    "Shocked": [],
    "Sorry": [],
    "Surprise": [],

    # **********
    # WRN: skipping the anim 'Excited' (already in another library)
    # WRN: skipping the anim 'Excited' (already in another library)
    # WRN: skipping the anim 'Excited' (already in another library)
    # WRN: skipping the anim 'Enthusiastic' (already in another library)
    # WRN: skipping the anim 'Shy' (already in another library)
    # WRN: skipping the anim 'Shy' (already in another library)
    "Amused": [],
    "Confident": [],
    "Ecstatic": [],
    "Happy": [],
    "Hungry": [],
    "Hysterical": [],
    "Interested": [],
    "Laugh": [],
    "Mocker": [],
    "Optimistic": [],
    "Peaceful": [],
    "Proud": [],
    "Relieved": [],
    "Sure": [],
    "Winner": [],
}